"""Quick CLI for generating reports via the production API.

Usage:
    python scripts/generate_report.py "Stripe" "FinTech" "competitive" "What is the competitive landscape for payment processing?"
    python scripts/generate_report.py "My Startup" "SaaS" "market_sizing" "What is the TAM for AI writing tools?"

Reports are saved as markdown files in the current directory.
"""

import json
import os
import sys

import requests
from dotenv import load_dotenv

load_dotenv()

API_URL = os.environ.get("INSIGHTFORGE_URL", "https://insightforge.azriel.io")
ADMIN_KEY = os.environ.get("ADMIN_API_KEY", "")


def generate(company: str, industry: str, analysis_type: str, question: str):
    print(f"Generating {analysis_type} report for {company}...")
    print(f"API: {API_URL}")

    resp = requests.post(
        f"{API_URL}/api/v1/analyze",
        json={
            "company_name": company,
            "industry": industry,
            "analysis_type": analysis_type,
            "question": question,
        },
        headers={"X-Admin-Key": ADMIN_KEY},
        timeout=180,
    )

    if resp.status_code != 200:
        print(f"ERROR {resp.status_code}: {resp.text}")
        sys.exit(1)

    data = resp.json()
    report_id = data["id"]
    filename = f"{company.lower().replace(' ', '_')}_{analysis_type}_{report_id}.md"

    # Write markdown report
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# {company} — {analysis_type.replace('_', ' ').title()} Report\n\n")
        f.write(f"**Generated**: {data['created_at'][:10]}  \n")
        f.write(f"**Industry**: {industry}  \n")
        f.write(f"**Question**: {question}  \n")
        f.write(f"**Report ID**: {report_id}  \n\n")
        f.write("---\n\n")
        f.write(data["full_report"])
        f.write("\n\n---\n\n")
        f.write(f"*Generated by InsightForge in {data['generation_time_seconds']}s*\n")

    print(f"Done! Report saved to: {filename}")
    print(f"  Words: ~{len(data['full_report'].split())}")
    print(f"  Time: {data['generation_time_seconds']}s")
    print(f"  Tokens: {data['estimated_tokens_used']}")
    print(f"  View online: {API_URL}/report/{report_id}")

    return data


if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: python generate_report.py <company> <industry> <type> <question>")
        print("Types: comprehensive, competitive, swot, market_sizing")
        sys.exit(1)

    generate(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
